spring:
  datasource:
    url: jdbc:mysql://localhost:3306/collaborative_shopping_squad?useSSL=false
    username: root
    password: rootoor
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
