spring:
  profiles:
    include:
      - database
  jpa:
    hibernate:
      ddl-auto: none
cors:
  allow:
    origins: http://localhost:5173
# JWT
jwt:
  expiredMs: 60
  issuer: test@test.com
  secret_key: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb
