spring:
  profiles:
    include:
      - database
cors:
  allow:
    origins: http://localhost:5173
# JWT
jwt:
  expiredMs: 60
  issuer: test@test.com
  secret_key: testProjectTestJwtProjectTest@Test.com/TestProjectTestJwtProjectTestTestTest
